version: '3.5'
services:
  frontend:
    restart: always
    container_name: giga.proxy
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile:
        ./docker/Dockerfile
    volumes:
      - .:/proxy
      - ./logs/nginx/:/logs
    logging:
      options:
        max-size: 100m
  haproxy-lb:
    image: haproxy:alpine
    restart: always
    container_name: giga.haproxy
    ports:
      - "8081:8081"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    logging:
      options:
        max-size: 10m
